# Generated by Django 3.1.7 on 2021-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210503_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='contactno',
            field=models.CharField(default='', editable=False, max_length=12),
        ),
    ]
