# Generated by Django 3.2 on 2021-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contact_number',
        ),
    ]
