# Generated by Django 3.2 on 2021-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_feedback_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email_id', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('order_list', models.CharField(max_length=250)),
                ('paid_payment', models.IntegerField(max_length=250)),
                ('remaining_payment', models.CharField(max_length=250)),
                ('total_payment', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
