# Generated by Django 3.2 on 2021-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_name', models.CharField(max_length=250)),
                ('list_of_medicine_name', models.CharField(max_length=250)),
                ('amount_of_medicine', models.IntegerField(max_length=250)),
                ('price_of_medicine', models.IntegerField(max_length=250)),
                ('manufacture_date', models.IntegerField(max_length=250)),
                ('expiry_date', models.IntegerField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
