# Generated by Django 3.2 on 2021-05-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_salesrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='list_of_medicine_name',
            new_name='medicine_name',
        ),
    ]
