# Generated by Django 3.2 on 2021-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_rename_list_of_medicine_name_salesrecord_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='expiry_date',
            field=models.DateField(max_length=250),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='manufacture_date',
            field=models.DateField(max_length=250),
        ),
    ]
