# Generated by Django 3.2 on 2021-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine_Name', models.CharField(max_length=122)),
                ('No_of_strips', models.CharField(max_length=12)),
                ('NO_of_medicine', models.CharField(max_length=12)),
            ],
        ),
    ]
