# Generated by Django 3.2 on 2021-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Medical_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Medicine_Name',
            field=models.CharField(max_length=50),
        ),
    ]
