# Generated by Django 3.2 on 2021-05-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgotpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('newpassword', models.CharField(max_length=50)),
                ('confpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
