# Generated by Django 3.2 on 2021-05-08 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210509_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='companyname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
