# Generated by Django 3.2 on 2021-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
