# Generated by Django 3.2 on 2021-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
