# Generated by Django 3.2 on 2021-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
