# Generated by Django 3.2 on 2021-05-22 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210523_0110'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='newfeedback',
            old_name='suggetion',
            new_name='suggestion',
        ),
        migrations.AddField(
            model_name='newfeedback',
            name='star',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
