# Generated by Django 3.2 on 2021-05-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210523_0153'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='newfeedback',
            name='star',
        ),
    ]
