# Generated by Django 3.2 on 2021-05-23 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210523_1408'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='newfeedback',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newfeedback',
            name='suggestion',
            field=models.CharField(max_length=500),
        ),
    ]
