# Generated by Django 3.2 on 2021-05-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210523_2345'),
    ]

    operations = [
       
    ]
