# Generated by Django 3.2 on 2021-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210523_2348'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
