# Generated by Django 3.2 on 2021-05-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210524_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=122)),
                ('contactno', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('re_password', models.CharField(max_length=40)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('medicalno', models.CharField(max_length=50, null=True)),
                ('maddress', models.CharField(max_length=500, null=True)),
            ],
        ),
        
    ]
