# Generated by Django 3.2 on 2021-05-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210530_1252'),
    ]

    operations = [
       
    ]
