# Generated by Django 3.1.7 on 2021-06-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210609_2318'),
    ]

    