# Generated by Django 3.1.7 on 2021-06-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20210610_0005'),
    ]

    
